  ------------------------------------------------------------------------------
  --- 1 - TABLA TIPO PROPIEDAD
  ------------------------------------------------------------------------------

    CREATE TABLE "TIPO_PROPIEDAD" 
   (  "ID_TIPO_PROPIEDAD" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 10 MAXVALUE 100 INCREMENT BY 3 START WITH 10 NOT NULL ENABLE, 
	    "TIPO_PROPIEDAD" VARCHAR2(30 BYTE), 
		CONSTRAINT "ID_TIPO_PROPIEDAD_PK" PRIMARY KEY ("ID_TIPO_PROPIEDAD")
   );
   
   --1.1. INSERT TABLA TIPO PROPIEDAD
   INSERT INTO TIPO_PROPIEDAD (TIPO_PROPIEDAD) VALUES ('CASA');
   INSERT INTO TIPO_PROPIEDAD (TIPO_PROPIEDAD) VALUES ('DEPARTAMENTO');
   INSERT INTO TIPO_PROPIEDAD (TIPO_PROPIEDAD) VALUES ('LOCAL');
   INSERT INTO TIPO_PROPIEDAD (TIPO_PROPIEDAD) VALUES ('PARCELA SIN CASA');
   INSERT INTO TIPO_PROPIEDAD (TIPO_PROPIEDAD) VALUES ('PARCELA CON CASA');
--
--
--
--
--
--------------------------------------------------------------------------------
--- 2 - TABLA ESTADO CIVIL
--------------------------------------------------------------------------------

  CREATE TABLE "ESTCIVIL" 
   (	"ID_ESTCIVIL" NUMBER(1,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 1 NOT NULL ENABLE, 
	"ESTADO_CIVIL" NUMBER DEFAULT 10, 
	CONSTRAINT "ID_ESTCIVIL_PK" PRIMARY KEY ("ID_ESTCIVIL")
   );
  
---2.1. insert tabla estado civil

INSERT INTO ESTCIVIL (ESTADO_CIVIL) VALUES (10);
INSERT INTO ESTCIVIL (ESTADO_CIVIL) VALUES (12);
INSERT INTO ESTCIVIL (ESTADO_CIVIL) VALUES (14);
INSERT INTO ESTCIVIL (ESTADO_CIVIL) VALUES (16);
INSERT INTO ESTCIVIL (ESTADO_CIVIL) VALUES (18);
--
--
--
--
--
  --------------------------------------------------------------------
  --3. TABLA CLIENTE
  --------------------------------------------------------------------
  
    CREATE TABLE "CLIENTE" 
   (	"NUMRUT_CLI" NUMBER(10,0) NOT NULL ENABLE, 
	"DVRUT_CLI" VARCHAR2(1 CHAR) NOT NULL ENABLE , 
	"APPPATERNO_CLI" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"APPMATERNO_CLI" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NOMBRE_CLI" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DIRECCION_CLI" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ID_ESTCIVIL" NUMBER NOT NULL ENABLE, 
	"FONOFIJO_CLI" NUMBER(15,0), 
	"CELULAR_CLI" NUMBER(15,0) NOT NULL ENABLE, 
	"RENTA_CLI" NUMBER(8,0) NOT NULL ENABLE, 
	CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("NUMRUT_CLI"),
	CONSTRAINT "CLIENTE_ESTCIVIL_FK1" FOREIGN KEY ("ID_ESTCIVIL")
	  REFERENCES "ESTCIVIL" ("ID_ESTCIVIL") ENABLE

   );

---3.1. INSERT TABLA CLIENTE
   INSERT INTO CLIENTE
   (NUMRUT_CLI, DVRUT_CLI, APPPATERNO_CLI, APPMATERNO_CLI, NOMBRE_CLI, DIRECCION_CLI, ID_ESTCIVIL, FONOFIJO_CLI, CELULAR_CLI, RENTA_CLI)
VALUES
   (1999771, '1', 'vallejos', 'carreno', 'valeria', 'leo 80', 1, 9991112, 9991112, 1000000);
   INSERT INTO CLIENTE
   (NUMRUT_CLI, DVRUT_CLI, APPPATERNO_CLI, APPMATERNO_CLI, NOMBRE_CLI, DIRECCION_CLI, ID_ESTCIVIL, FONOFIJO_CLI, CELULAR_CLI, RENTA_CLI)
VALUES
   (1770001, '1', 'vallejos', 'carreno', 'valeria', 'leo 80', 1, 9991112, 9991112, 1000000);

--
--
--
--
--
-----------------------------------------------------------------------------------------
---4. EMPLEADO --- EMPLEADO --- EMPLEADO --- EMPLEADO --- EMPLEADO--- EMPLEADO --- EMPLEADO
-----------------------------------------------------------------------------------------

  CREATE TABLE "EMPLEADO" 
   (	"NUMRUT_EMP" NUMBER(10,0) NOT NULL ENABLE, 
	"DVRUT_EMP" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"APPPATERNO_EMP" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"APPMATERNO_EMP" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NOMBRE_EMP" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DIRECCION_EMP" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ID_ESTCIVIL" NUMBER NOT NULL ENABLE, 
	"FONOFIJO_EMP" NUMBER(15,0), 
	"CELULAR_EMP" NUMBER(15,0) NOT NULL ENABLE, 
	"FECNAC_EMP" DATE NOT NULL ENABLE, 
	"FECING_EMP" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"SUELDO_EMP" NUMBER(7,0) NOT NULL ENABLE, 
	"ID_COMUNA" NUMBER NOT NULL ENABLE, 
	"ID_CATEGORIA_EMPLEADO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("NUMRUT_EMP"),
	 CONSTRAINT "EMPLEADO_COMUNA_FK1" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "COMUNA" ("ID_COMUNA") ENABLE, 
	 CONSTRAINT "EMPLEADO_CATEGORIA_FK1" FOREIGN KEY ("ID_CATEGORIA_EMPLEADO")
	  REFERENCES "CATEGORIA_EMPLEADO" ("ID_CATEGORIA_EMP") ENABLE, 
	 CONSTRAINT "EMPLEADO_ESTCIVIL_FK1" FOREIGN KEY ("ID_ESTCIVIL")
	  REFERENCES "ESTCIVIL" ("ID_ESTCIVIL") ENABLE
   );

---4.1. INSERT TABLA EMPLEADO
INSERT INTO EMPLEADO
   (NUMRUT_EMP, DVRUT_EMP, APPPATERNO_EMP, APPMATERNO_EMP, NOMBRE_EMP, DIRECCION_EMP, ID_ESTCIVIL, FONOFIJO_EMP, CELULAR_EMP, FECNAC_EMP, FECING_EMP, SUELDO_EMP, ID_COMUNA, ID_CATEGORIA_EMPLEADO)
VALUES
   (1234567890, '1', 'Gonzalez', 'Perez', 'Juan', 'Calle Principal 123', 1, 1234567, 987654321, TO_DATE('1990-01-01', 'YYYY-MM-DD'), SYSDATE, 5000000, 80, 1);
   INSERT INTO EMPLEADO
   (NUMRUT_EMP, DVRUT_EMP, APPPATERNO_EMP, APPMATERNO_EMP, NOMBRE_EMP, DIRECCION_EMP, ID_ESTCIVIL, FONOFIJO_EMP, CELULAR_EMP, FECNAC_EMP, FECING_EMP, SUELDO_EMP, ID_COMUNA, ID_CATEGORIA_EMPLEADO)
VALUES
   (17327394, '0', 'Corbacho', 'Moya', 'Andres', 'Calle Principal xxx', 1, 1234567, 987654321, TO_DATE('1987-10-02', 'YYYY-MM-DD'), SYSDATE, 5000000, 80, 1);
--
--
--
--
--
  -----------------------------------------------------------------------------------------------
  ---5. TABLA PROPIEDAD Y TRIGGERS    ---TABLA PROPIEDAD Y TRIGGERS   ---TABLA PROPIEDAD Y TRIGGERS 
  -----------------------------------------------------------------------------------------------
  
   CREATE TABLE "PROPIEDAD" 
   (	"NRO_PROPIEDAD" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOT NULL ENABLE, 
	"DIRECCION_PROPIEDAD" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"SUPERFICIE" NUMBER(8,2) NOT NULL ENABLE, 
	"NRO_DORMITORIOS" NUMBER(3,0) NOT NULL ENABLE, 
	"NRO_BANOS" NUMBER(2,0) NOT NULL ENABLE, 
	"VALOR_ARRIENDO" NUMBER(9,0) NOT NULL ENABLE, 
	"VALOR_GASTO_COMUN" NUMBER(6,0) NOT NULL ENABLE, 
	"ID_TIPO_PROPIEDAD" NUMBER NOT NULL ENABLE, 
	"ID_COMUNA" NUMBER NOT NULL ENABLE, 
	"NUMRUT_PROP" NUMBER(10,0) NOT NULL ENABLE, 
	"NUMRUT_EMP" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PROPIEDAD_PK" PRIMARY KEY ("NRO_PROPIEDAD"),
	 CONSTRAINT "TOPE_ARRIENDO_GASTOC_CHK1" CHECK (VALOR_ARRIENDO<250000000 AND VALOR_GASTO_COMUN<250000) ENABLE, 
	 CONSTRAINT "PROPIEDAD_EMPLEADO_FK1" FOREIGN KEY ("NUMRUT_EMP")
	  REFERENCES "EMPLEADO" ("NUMRUT_EMP") ENABLE, 
	 CONSTRAINT "PROPIEDAD_PROPIETARIO_FK1" FOREIGN KEY ("NUMRUT_PROP")
	  REFERENCES "PROPIETARIO" ("NUMRUT_PROP") ENABLE, 
	 CONSTRAINT "PROPIEDAD_COMUNA_FK1" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "COMUNA" ("ID_COMUNA") ENABLE, 
	 CONSTRAINT "PROPIEDAD_TIPO_PROPIEDAD_FK1" FOREIGN KEY ("ID_TIPO_PROPIEDAD")
	  REFERENCES "TIPO_PROPIEDAD" ("ID_TIPO_PROPIEDAD") ENABLE
   );
   

--- 5.1. INSERT TABLA PROPIEDAD

INSERT INTO PROPIEDAD
   (DIRECCION_PROPIEDAD, SUPERFICIE, NRO_DORMITORIOS, NRO_BANOS, VALOR_ARRIENDO, VALOR_GASTO_COMUN, ID_TIPO_PROPIEDAD, ID_COMUNA, NUMRUT_PROP, NUMRUT_EMP)
VALUES
   ('AVENIDA LAS CONDES 111', 120.50, 3, 2, 1500000, 50000, 13, 80, 12491094, 17327394);


---5.2. TRIGGERS SEGUN TIPO PROPIEDAD
   
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_INSERT_PROPIEDAD_19" 
BEFORE INSERT ON "PROPIEDAD"
FOR EACH ROW
BEGIN
  IF :NEW.ID_TIPO_PROPIEDAD = 19 THEN
    :NEW.NRO_DORMITORIOS := 0;
    :NEW.NRO_BANOS := 0;
  END IF;
END;

/
ALTER TRIGGER "TRG_INSERT_PROPIEDAD_19" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_INSERT_PROPIEDAD_16" 
BEFORE INSERT ON "PROPIEDAD"
FOR EACH ROW
BEGIN
  IF :NEW.ID_TIPO_PROPIEDAD = 16 THEN
    :NEW.NRO_DORMITORIOS := 0;
  END IF;
END;
/
ALTER TRIGGER "TRG_INSERT_PROPIEDAD_16" ENABLE;
--
--
--
--
--
-------------------------------------------------------------------
---6. TABLA ARRIENDO---TABLA ARRIENDO---TABLA ARRIENDO
------------------------------------------------------------------

  CREATE TABLE "ARRIENDO" 
   (	"ID_ARRIENDO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOT NULL ENABLE, 
	"NRO_PROPIEDAD" NUMBER NOT NULL ENABLE, 
	"FECINI_ARRIENDO" DATE NOT NULL ENABLE, 
	"FECTER_ARRIENDO" DATE, 
	"NUMRUT_CLI" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ARRIENDO_PK" PRIMARY KEY ("ID_ARRIENDO"),
	 CONSTRAINT "ARRIENDO_CLIENTE_FK1" FOREIGN KEY ("NUMRUT_CLI")
	  REFERENCES "CLIENTE" ("NUMRUT_CLI") ENABLE, 
	 CONSTRAINT "ARRIENDO_PROPIEDAD_FK1" FOREIGN KEY ("NRO_PROPIEDAD")
	  REFERENCES "PROPIEDAD" ("NRO_PROPIEDAD") ENABLE
   );
  
  ---6.1. INSERT TABLA ARRIENDO
INSERT INTO ARRIENDO (NRO_PROPIEDAD, FECINI_ARRIENDO, FECTER_ARRIENDO, NUMRUT_CLI)
VALUES (1, TO_DATE('2023-11-20', 'YYYY-MM-DD'), NULL, 1770001);
--
--
--
--
--
-------------------------------------------------------------------
---7. AGREGAR RELACION PROPIETARIO_ESTADO_CIVIL
------------------------------------------------------------------
ALTER TABLE PROPIETARIO
   ADD CONSTRAINT PROPIETARIO_ESTCIVIL_FK FOREIGN KEY (ID_ESTCIVIL)
   REFERENCES ESTCIVIL (ID_ESTCIVIL);


--8. check digito verificador
ALTER TABLE "CLIENTE"
ADD CONSTRAINT CHK_DVRUT_CLI CHECK (DVRUT_CLI IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K'));

ALTER TABLE "EMPLEADO"
ADD CONSTRAINT CHK_DVRUT_EMP CHECK (DVRUT_EMP IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K'));

ALTER TABLE "PROPIETARIO"
ADD CONSTRAINT CHK_DVRUT_PROP CHECK (DVRUT_PROP IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K'));

--8.1 Check mtr de superficie validos
ALTER TABLE "PROPIEDAD"
ADD CONSTRAINT "PROPIEDAD_CHECK_SUPERFICIE" CHECK (SUPERFICIE > 0);

--9. Correccion not null de comuna en tabla propietario
ALTER TABLE "PROPIETARIO"
MODIFY ("ID_COMUNA" NUMBER NOT NULL);